# Generated by Django 3.1.3 on 2020-11-25 20:52

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('email', models.EmailField(max_length=254)),
                ('addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='alert',
            index=django.contrib.postgres.indexes.GinIndex(fields=['addresses'], name='active_addresses'),
        ),
    ]
