# Generated by Django 3.1.3 on 2020-11-26 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201126_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateTimeField(auto_now_add=True)),
                ('body', models.JSONField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alert')),
            ],
            options={
                'ordering': ('-received',),
            },
        ),
        migrations.AddIndex(
            model_name='webhookdata',
            index=models.Index(fields=['alert_id', 'received'], name='alert_by_received'),
        ),
    ]
